# =========================================================
#
# This file allows anyone to start the CopyPatrol web interface
# locally. Additional configuration on the `.env.local` file is still
# required to bring this up.
#
# Ensure the following before bringing services from this file up (in order):
#  - Images must be built (see README)
#  - Composer packages must be installed (see README)
#  - `.env.local` contains appropriate credentials (see README)
#    - `REPLICAS_USERNAME` and `REPLICAS_PASSWORD` must be supplied
#    - `TOOLSDB_USERNAME` and `TOOLSDB_PASSWORD` must be supplied
#    - `TOOLSDB_HOST` and `REPLICAS_HOST_*` must be `toolforge-gateway.internal`
#
# =========================================================

services:
    copypatrol:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: development
        image: wikimedia/copypatrol:development
        command: serve
        stdin_open: true
        tty: true
        environment:
            - TROVE_REMOTE_HOST
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "8000:8000"
        volumes:
            # This binds your SSH configuration into the container.
            # If you don't want to do this, comment this entry out.
            # TODO: Disable `copypatrol` user access to /ssh, when that becomes possible.
            # https://github.com/docker/roadmap/issues/398
            -   type: bind
                source: "$HOME/.ssh"
                target: "/ssh"
                read_only: true
            # This will bind the files in the development directory to the app.
            -   type: bind
                source: "."
                target: "/app"
                read_only: true
            -   type: bind
                source: "./var"
                target: "/app/var"
        stop_signal: SIGINT
